### PR TITLE
Beautified my website and fixed Sawyer's upon his request

### PR DESCRIPTION
**Pull request by AMathGTCHS**

### CODE REVIEW

**Comment by draygtchs** [comment]
Why are you submitting a second pull request?

**Comment by draygtchs** [comment]
This seems suspicious. @import url('https://fonts.googleapis.com/css2?family=Rubik:ital,wght@0,300..900;1,300..900&display=swap');

**Comment by AMathGTCHS** [comment]
In isaac.css, there is a similar import...

`@import url('https://fonts.googleapis.com/css2?family=Poppins:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap');`

If you're alright with his, mine is just a different font from the same website.

**Comment by AMathGTCHS** [comment]
@Isaac-Boroughs what do you have to say about this 

🤔

**Comment by draygtchs** [comment]
Declined.

**Pull request closed without merging**
